version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      container_name: app-server

    ports: -"3000:3000"

    enviroment:
      - NODE_ENV=production
      - PORT=3000

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      container_name: app-client

    ports:
      - "5173:5173"

    enviroment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000

    depends_on:
      server:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5173",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    restart: unless-stopped
