name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build-client:
    runs-on: ubuntu-latest
    name: Build Client
    steps:
      - name: Use Node.js
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install Client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build Server
        working-directory: ./client
        run: npm run build

  build-sever:
    runs-on: ubuntu-latest
    name: Build Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: server/package-lock.json

      - name: Install Server dependencies
        working-directory: ./server
        run: npm ci
